---
title: "AMATH 351 Homework 2"
subtitle: "Linear ODEs, Exact ODEs, and Substitution"
author: "Jaiden Atterbury"
date: "2023-04-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Exercise 1: Linear first order ODEs.** Find the general solution for the following ODEs:

1. $ty'+y=3t^2-1, \ \ \ t > 0$

This equation is a linear equation, so usually we'd have to identify $p(t)$ and solve for the integrating factor $\mu(t)=e^{\int p(t)dt}$. However, notice that this equation is equivalent to $\frac{d}{dt}(ty) = 3t^2-1$. Integrating both sides with respect to $t$ give us $ty = t^3 - t + C$, where $C \in \mathbb{R}$ is a constant of integration. Since $t > 0$ we have run into no trouble dividing by $t$, thus isolating $y$ gives us our explicit general solution of $y(t) = t^2-1+\frac{C}{t}, \ \ t > 0$.

2. $y' - \frac{y}{t} = t^2, \ \ \ t \neq 0$

This equation is a linear equation, and unlike the last problem we will have to solve for the integrating factor. First, notice that the equation is already in the form of $\frac{dy}{dt}+p(t)y=g(t)$ so we can see that $p(t)=\frac{-1}{t}$ and $g(t) = t^2$. Next we will find the integrating factor defined as $\mu(t) = e^{\int p(t)dt}$, in our case, $\mu(t) = e^{\int \frac{-1}{t}dt} = e^{\ln\left|\frac{1}{t}\right|} = \left|\frac{1}{t}\right|$. Notice however, since $\mu(t) = \left|\frac{1}{t}\right|$ we can split our general solution into two case: the case where $t > 0$ and the case where $t < 0$.

**Branch 1:** $\\$
In the case where $t > 0$ this implies that $\mu(t) = \frac{1}{t}$. Multiplying our differential equation by the integrating factor yields the new equation $\frac{1}{t}y'-\frac{1}{t^2}y = t$. Notice that this equation is equivalent to $\frac{d}{dt}(\frac{1}{t}y)=t$. Integrating both sides with respect to $t$ gives us $\frac{1}{t}y = \frac{1}{2}t^2 + C$, where $C \in \mathbb{R}$ is a constant of integration. Isolating $y$ gives us our first branch of the general solution $y(t) = \frac{1}{2}t^3+Ct, \ \ t > 0$.

**Branch 2:** $\\$
In the case where $t < 0$ this implies that $\mu(t) = \frac{-1}{t}$. Multiplying our differential equation by the integrating factor yields the new equation $\frac{-1}{t}y'+\frac{1}{t^2}y = -t$. Notice that this equation is equivalent to $\frac{d}{dt}(\frac{-1}{t}y)=-t$. Integrating both sides with respect to $t$ gives us $\frac{-1}{t}y = \frac{-1}{2}t^2 + C$, where $C \in \mathbb{R}$ is a constant of integration. Isolating $y$ gives us our second branch of the general solution $y(t) = \frac{1}{2}t^3 - Ct, \ \ t < 0$.

Thus our general solution to the ODE is
\begin{align*} 
y(t) &= \left \{ 
\begin{array}{cc}
                \frac{1}{2}t^3 + Ct, \ \ \ t > 0 \\
                \frac{1}{2}t^3 - Ct  \ \ \ t < 0
\end{array} \right.
\end{align*}

Again with the constraint that $t \neq 0$.

3. $y'+2ty=2te^{-t^2}$

This equation is a linear equation. To solve, we must first notice that the equation is already in the form of $\frac{dy}{dt}+p(t)y=g(t)$ so we can see that $p(t)=2t$ and $g(t) = 2te^{-t^2}$. Next we will find the integrating factor defined as $\mu(t) = e^{\int p(t)dt}$, in our case, $\mu(t) = e^{\int 2tdt} = e^{t^2}$. Multiplying our differential equation by the integrating factor yields the new equation $e^{t^2}y' +2te^{t^2}y = 2t$. Notice that this equation is equivalent to $\frac{d}{dt}(e^{t^2}y)=2t$. Integrating both sides with respect to $t$ gives us $e^{t^2}y = t^2 + C$, where $C \in \mathbb{R}$ is a constant of integration. Isolating $y$ gives us our explicit general solution $y(t) = Ce^{-t^2} + t^2e^{-t^2}$.

4. $y' + y = \frac{1}{1+e^{2t}}$

This equation is a linear equation. To solve, we must first notice that the equation is already in the form of $\frac{dy}{dt}+p(t)y=g(t)$ so we can see that $p(t)=1$ and $g(t) = \frac{1}{1+e^{2t}}$. Next we will find the integrating factor defined as $\mu(t) = e^{\int p(t)dt}$, in our case, $\mu(t) = e^{\int dt} = e^t$. Multiplying our differential equation by the integrating factor yields the new equation $e^{t}y' +e^{t}y = \frac{e^t}{1+e^{2t}}$. Notice that this equation is equivalent to $\frac{d}{dt}(e^{t}y)=\frac{e^t}{1+e^{2t}}$. Integrating both sides with respect to $t$ gives us $e^{t^2}y = \int \frac{e^t}{1+e^{2t}} dt$. In order to solve the integral on the right hand side we will have to make a substitution. In particular let $u = e^t \implies du = e^tdt$, thus our integral becomes $\int \frac{1}{u^2 + 1} du$ which equals $\arctan(u) + C$, where $C \in \mathbb{R}$ is a constant of integration. Plugging back in $u = e^x$ we get the equation $e^ty = \arctan(e^t) + C$. Isolating $y$ gives us our explicit general solution $y(t) = Ce^{-t} + \arctan(e^t)e^{-t}$.

**Exercise 2: Generalized solution**. Solve the IVP:
\begin{align*}
y' &= p(t)y = 0 \ \ \ y(0) = 1
\end{align*}
with
\begin{align*} 
p(t) &= \left \{ 
\begin{array}{cc}
                2, \ \ \ 0 \leq t \leq 1 \\ 
                1, \ \ \ \ \ \ \ \ t > 1
\end{array} \right.
\end{align*}

Since at $t = 1$ there is a jump discontinuity in $p(t)$, in order to solve this IVP we must solve the equation separately for $0\leq t \leq1$ and $t > 1$. This means we must solve $y' +2y = 0, \ \ y(0) = 1, \ \ 0 \leq t \leq1$ and $y'+ y=0, \ \ t > 0$ simultaneously. Afterward, we must choose a constant that makes the two solutions matched so that y is continuous at $t = 1$.

First we'll solve the initial value problem $y' +2y = 0, \ \ y(0) = 1, \ \ 0 \leq t \leq1$. This equation is a linear equation. To solve, we must first notice that the equation is already in the form of $\frac{dy}{dt}+p(t)y=g(t)$ so we can see that $p(t)=2$ and $g(t) = 0$. Next we will find the integrating factor defined as $\mu(t) = e^{\int p(t)dt}$, in our case, $\mu(t) = e^{\int 2dt} = e^2t$. Multiplying our differential equation by the integrating factor yields the new equation $e^{2t}y' +e^{2t}y = 0$. Notice that this equation is equivalent to $\frac{d}{dt}(e^{2t}y)=0$. Integrating both sides with respect to $t$ gives us $e^{2t}y = C$, where $C \in \mathbb{R}$ is a constant of integration. Isolating $y$ gives us our explicit general solution $y(t) = Ce^{-2t}$. Plugging in our initial condition $y(0) = 1$ we see that our particular solution is $y^{I}(t) = e^{2t}$

Next we'll solve the equation $y'+ y=0, \ \ t > 0$. This equation is a linear equation. To solve, we must first notice that the equation is already in the form of $\frac{dy}{dt}+p(t)y=g(t)$ so we can see that $p(t) = 1$ and $g(t) = 0$. Next we will find the integrating factor defined as $\mu(t) = e^{\int p(t)dt}$, in our case, $\mu(t) = e^{\int dt} = e^t$. Multiplying our differential equation by the integrating factor yields the new equation $e^{t}y' +e^{t}y = 0$. Notice that this equation is equivalent to $\frac{d}{dt}(e^{t}y)=0$. Integrating both sides with respect to $t$ gives us $e^{t}y = C$, where $C \in \mathbb{R}$ is a constant of integration. Isolating $y$ gives us our explicit general solution $y^{II}(t) = Ce^{-t}$.

Now we must find the value of $C$ that will make $y$ continuous at $t = 1$. We can find this $C$ by taking the limit as t approaches 1 from both sides and setting them equal to each other and solving for $C$. With that said, $\lim_{t \to 1^{-}} y^{I}(t) = e^{-2(1)} = e^{-2}$ and
$\lim_{t \to 1^{+}} y^{II}(t) = Ce^{-1}$. Setting these two limits together we see that $C = \frac{1}{e}$. Plugging this into $y^{II}(t)$ we get our particular solution:
\begin{align*} 
y(t) &= \left \{ 
\begin{array}{cc}
                y^{I}(t) = e^{-2t}, \ \ \ 0 \leq t \leq 1 \\
                y^{II}(t) = \frac{1}{e^{t+1}} \ \ \ t > 1
\end{array} \right.
\end{align*}

**Exercise 3: Solving ODEs by substitution.** Find the general solution for the following ODEs by performing the substitutions indicated:

1. $\frac{dy}{dt} = 2t + y$. Substitution: $u = 2t + y$.

If we let $u = 2t + y$, this implies that $u'=2+y'$. It follows that $u'= 2 + 2t + y$ which equals $u' = 2 + u$. However, notice that this equation is separable. Written in separable form:
\begin{align}
\frac{du}{u+2} &= dt
\end{align}
Condition in which separable form in (1) is valid:
\begin{align*}
u &\neq -2
\end{align*}
Now we must integrate both sides of the equation:
\begin{align*}
\int\frac{dy}{u+2} &= \int dt + \text{C} \\
\ln|u+2| &= t + \text{C}
\end{align*}
where $C \in \mathbb{R}$. Now we must isolate $u$ to get an explicit general solution:
\begin{align*}
|u+2| &= e^c e^t \\
u+2 &= \pm e^c e^t \\
u &= \pm e^c e^t - 2
\end{align*}
If we let $D = \pm e^{\text{C}} \in \mathbb{R}$, then we get:
\begin{align*}
u &= De^t - 2
\end{align*}
Now that we have the general form of $u(t)$, we must switch back to the variable $y$. Switching back to the variable y leads us to the general solution:
\begin{align*}
y(t) &= De^t -2t - 2
\end{align*}

2. $\frac{dy}{dt} = \frac{1}{t - y} + 1$. Substitution: $u = t - y$.

If we let $u = t - y$, this implies $u' = 1 - y'$. It follows that $u'= \frac{-1}{t-y}$ which equals $u' = \frac{-1}{u}, \  u \neq 0$. However, notice that this equation is separable. Written in separable form:
\begin{align*}
u du &= -dt
\end{align*}
Now we must integrate both sides of the equation:
\begin{align*}
\int u du &= -\int dt + \text{C} \\
\frac{1}{2}y^2 &= t + \text{C}
\end{align*}
where $C \in \mathbb{R}$. Now we must isolate $u$ to get an explicit general solution:
\begin{align*}
u^2 &= -2t + 2C \\
u = \pm \sqrt{2C - 2t}
\end{align*}
If we let $D = 2C \in \mathbb{R}$, then we get:
\begin{align*}
u &= \pm \sqrt{D - 2t}
\end{align*}
Notice however, since $u \neq 0 \implies t-y \neq 0 \implies y \neq t$. To obtain the general solution, we must plug $t - y$ in for $u$ doing so we obtain the equation
\begin{align*}
y(t) = t \pm \sqrt{D - 2t}
\end{align*}
Furthermore, $D - 2t \geq 0$. However if $D - 2t = 0$, then $y = t$, but $y \neq t$ thus $D - 2t > 0 \implies t < \frac{D}{2}$. Thus the general solution to this ODE is $y(t) = t \pm \sqrt{D - 2t}, \ t < \frac{D}{2}$.

3. $y^2dt-t(t+y)dy=0$. Substitution: $u = y/t$. $\\$
Check also that this is not an exact ODE.

In order to show that the above ODE is not exact, we must check if the compatibility condition is violated. The compatibility condition states that an $F(x, y)$ exists such that $\frac{\partial F}{\partial t} = M(t, y)$, $\frac{\partial F}{\partial y} = N(t, y)$ if and only if $\frac{\partial M}{\partial y} = \frac{\partial N}{\partial t}$. In the above ODE $M(t, y) = y^2$ and $N(t, y) = -t^2-ty)$ which implies that $\frac{\partial M}{\partial y} = 2y$ and $\frac{\partial N}{\partial t} = -2t-y$. Therefore the ODE is not exact.

Rewriting our ODE in a nicer form we notice that $\frac{dy}{dt} = \frac{y^2}{t(t+y)}$ which implies that $t \neq 0$ and $y \neq -t \implies y \neq 0$, hence $y(t) = 0$ is a solution to the ODE. If we let $u = \frac{y}{t}$, then $u' = \frac{1}{t}y'-\frac{1}{t^2}y = \frac{1}{t}y'-\frac{1}{t}u$. Now after the substitution our ODE becomes $\frac{du}{dt} = \frac{y^2}{t^2(t + y)} - \frac{u}{t}$. Using the fact that $u = \frac{y}{t}$ we obtain the equation $\frac{du}{dt} = \frac{u^2}{(t + y)} - \frac{u}{t}$. We will now do some simplification to get the ODE into a separable from
\begin{align*}
u' &= \frac{tu^2-(t+y)u}{t(t+y)} \\
&= \frac{tu^2-tu-yu}{t^2+yt} \\
&= \frac{tu^2-tu-tu^2}{t^2+t^2u} \quad \text{(Since $y = ut$)} \\
&= \frac{-u}{t(u + 1)} \quad \text{($u \neq 0, -1$)}
\end{align*}

However, notice that this equation is separable. Written in separable form:
\begin{align}
\frac{u+1}{u}du &= \frac{-1}{t} dt
\end{align}
Condition in which separable form in (1) is valid:
\begin{align*}
u &\neq 0
\end{align*}
Now we must integrate both sides of the equation:
\begin{align*}
\int du + \int \frac{1}{u}du &= \int -\frac{1}{t} dt + \text{C} \\
u + \ln|u| &= \ln|\frac{1}{t}| + \text{C}
\end{align*}
where $C \in \mathbb{R}$. Now that we have the general form of $u(t)$, we must switch back to the variable $y$. Switching back to the variable y leads us to the equation:
$\frac{y}{t} + \ln|\frac{y}{t}| = \ln|\frac{1}{t}| + \text{C}$. Exponentiating both sides yields the new equation $|\frac{y}{t}|e^{\frac{y}{t}} = e^C|\frac{1}{t}|$. After removing the absolute value signs we obtain the equation $\frac{y}{t}e^{\frac{y}{t}} = \pm e^C\frac{1}{t}$. If we let $D = \pm e^C \in \mathbb{R}$ then our equation simplifies to $\frac{y}{t}e^{\frac{y}{t}} = \frac{D}{t}$ and hence if $t \neq 0$ after multiplying by $t$ we obtain the implicit general solution $ye^{\frac{y}{t}} = D$.

**Exercise 4: Riccati equation** Let us consider the ODE of the form 
\begin{align}
y'+p(t)y+q(t)y^2=f(t)
\end{align}

1. Assume that we know a specific solution of Eq. (2), denoted as $y_1(t)$. Show that the substitution $y(t) = y_1(t)+u(t)$ transforms Eq. (2) into a Bernoulli equation. Hint: You should use the fact that $y_1$ satisfies Eq. (2).

If $y'+p(t)y(t)+q(t)y(t)^2=f(t)$, then we can rewrite the equation isolating $y'$ and obtain $y'=f(t)-p(t)y(t)-q(t)y(t)^2$. If we let $y(t) = y_1(t)+u(t)$, then it follows that $y'(t)=y_1'(t) + u'(t)$. Since $y_1(t)$ is a solution to the ODE then we know that $y_1'(t) = f(t)-p(t)y_1(t)-q(t)y_1(t)^2$. With this information we can now say $f(t)-p(t)y(t)-q(t)y(t)^2=f(t)-p(t)y_1(t)-q(t)y_1(t)^2 + u'(t)$. After isolating $u'(t)$ we obtain $u'(t) = p(t)y_1(t) - p(t)y(t) + q(t)y_1(t)^2 - q(t)y(t)^2$. Our next step in the simplification is noting that we can plug $y(t) = y_1(t) + u(t)$ into the equation. The next step is laborious simplification:
\begin{align*}
u'(t) &= p(t)y_1(t) - p(t)(y_1(t)+u(t)) + q(t)y_1(t)^2 - q(t)(y_1(t) + u(t))^2 \\
&= p(t)y_1(t) - p(t)y_1(t) + p(t)q(t) + q(t)y_1(t)^2 -q(t)(y_1(t)^2 + 2y_1(t)u(t) + u(t)^2) \\
&= p(t)q(t) + q(t)y_1(t)^2 -q(t)y_1(t)^2 - 2y_1(t)u(t)q(t) - q(t)u(t)^2 \\
&= p(t)q(t) - 2y_1(t)u(t)q(t) - q(t)u(t)^2 \\
&= -(2y_1(t)q(t) + p(t))u(t) - q(t)u(t)^2
\end{align*}

Recalling that the form of a Bernoulli equation is $y'+a(t)y=b(t)y^r$, we can see that the Riccati equation after the substitution, $u'(t) + (2y_1(t)q(t) + p(t))u(t) = -q(t)u(t)^2$, is in fact a Bernoulli equation.

Let us now consider one particular Riccati equation
\begin{align}
y' = 1+t^2-2ty+y^2 = 1+(y-t)^2
\end{align}

2. Check that $y_1(t) = t$ is a specific solution of Eq. (3). Using $y_1 = t$, and the substitution $y(t) = y_1(t) + u(t)$, find the general solution of Eq. (3).

To check that $y_1(t) = t$ is a specific solution of Eq. (3), we must take the derivative of $y_1(t)$ and plug it in to the ODE along with $y_1(t)$. With that said, $y_1'(t) = 1$, thus it follows that $y' = 1+t^2-2ty+y^2$ turns into $1 + 2t\cdot t = 1 + t^2$. Since $1+t^2=1+t^2$ we can see $y_1(t) = t$ is a specific solution of Eq. (3).

Using $y_1 = t$, and the substitution $y(t) = y_1(t) + u(t)$ we can find the general solution of Eq. (3). by following the Bernoulli equation we found in question 1. In question 1 we found that after using the above substitution on a Riccati equation of the form $y'+p(t)y+q(t)y^2=f(t)$ we were left with the Bernoulli equation $u'(t) + (2y_1(t)q(t) + p(t))u(t) = -q(t)u(t)^2$. Rearranging the given ODE into the given Ricatti from we obtain $y' + 2ty - y^2 = 1+t^2$ and hence we can see that $p(t) = 2t$, $q(t) = -1$, $f(t) = 1+t^2$, and $y_1(t) = t$. Plugging these functions into the Bernoulli form computed in question 1 we obtain the new ODE $u' = u^2$.

If we let $v = u^{-1}$, then $v' = -u^{-2}u'$ and thus $v' = -1$. This equation is separable, but its simple enough to see that $v = -t + C$ where $C \in \mathbb{R}$ is a constant. Replacing $v$ with $u^{-1}$ we obtain the equation $\frac{1}{u} = -t + C, \ u \neq 0$ and hence it follows that $u(t) = \frac{1}{-t+C}$ and hence the general solution to the Ricatti equation is $y(t) = y_1(t) + u(t)$ which equals $y(t) = t + \frac{1}{C - t}, \ t \neq C$.

Notice that the second substitution wasn't necessary as $u' = u^2$ is already separable.

3. Check that the solution of Eq. (3) is alternatively obtained by the substitution $z = y - t$.

If we let $z = y - t$, then $z' = y' - 1$. Thus $z' = (y - t)^2$, which equals $z' = z^2$. Again, if we let $s = z^{-1}$, then $s' = -z^{-2}z'$. Solving for $s$ we see that the ODE is separable, but like the last part this can easily be done by inspection and thus $s = t + C$ where $C \in \mathbb{R}$ is a constant. Replacing $s$ with $\frac{1}{z}$ we obtain the equation $\frac{1}{z} = -t + C, \ z \neq 0$. Isolating $z$ we get $z = \frac{1}{-t + C}$. Lastly, replacing $z$ with $y- t$ we obtain the general solution of the ODE which is $y(t) = t + \frac{1}{C-t}, \ t \neq C$. This confirms our answer from the last problem

Again, notice that the second substitution wasn't necessary as $v' = v^2$ is already separable.

**Exercise 5: Exact equations.** Show that the following ODEs are exact and find their general solution

1. $\frac{y}{x^2}dx - \frac{1}{x}dy = 0, \ x \neq 0$

In order to show that the above ODE is exact, we must check if the compatibility condition holds. The compatibility condition states that an $F(x, y)$ exists such that $\frac{\partial F}{\partial x} = M(x, y)$, $\frac{\partial F}{\partial y} = N(x, y)$ if and only if $\frac{\partial M}{\partial y} = \frac{\partial N}{\partial x}$. In the above ODE $M(x, y) = \frac{x}{y^2}$ and $N(x, y) = \frac{-1}{x}$ which implies that $\frac{\partial M}{\partial y} = \frac{1}{x^2}$ and $\frac{\partial N}{\partial x} = \frac{1}{x^2}$. Therefore the ODE is exact and we can continue with our solving method. First off we are looking for an $F(x, y)$ such that $\frac{\partial F}{\partial x} = M(x, y)$. By integrating both sides of the equality with respect to $x$ we obtain $F(x, y) = \frac{-y}{x} + h(y)$, where $h(y)$ is a function of y and acts as the constant of integration. Furthermore, if we take the partial derivative of $F(x, y)$ with respect to $y$ we obtain $\frac{\partial F}{\partial y} = \frac{-1}{x} + h'(y)$. We also want a function $F(x,y)$ such that $\frac{\partial F}{\partial y} = N(x, y)$. Hence if we set the two together we see that $\frac{-1}{x} = \frac{-1}{x} + h'(y) \implies 0 = h'(y) \implies c = h(y)$, however we can choose $c = 0$ in this case since we only need the simplest $h(y)$. Thus, since $\int dF(t, y) = 0 \implies F(t, y) = C$, we obtain the general solution $\frac{-y}{x} = C$. Isolating y we obtain $y(x) = -Cx, \ x \neq 0$ where $C \in \mathbb{R}$ is a constant.

2. $ye^{xy}dx + (3 + xe^{xy})dy = 0$

In order to show that the above ODE is exact, we must check if the compatibility condition holds. The compatibility condition states that an $F(x, y)$ exists such that $\frac{\partial F}{\partial x} = M(x, y)$, $\frac{\partial F}{\partial y} = N(x, y)$ if and only if $\frac{\partial M}{\partial y} = \frac{\partial N}{\partial x}$. In the above ODE $M(x, y) = ye^{xy}$ and $N(x, y) = 3 + xe^{xy}$ which implies that $\frac{\partial M}{\partial y} = xye^{xy} + e^{xy}$ and $\frac{\partial N}{\partial x} = xye^{xy} + e^{xy}$. Therefore the ODE is exact and we can continue with our solving method. First off we are looking for an $F(x, y)$ such that $\frac{\partial F}{\partial x} = M(x, y)$. By integrating both sides of the equality with respect to $x$ we obtain $F(x, y) = e^{xy} + h(y)$, where $h(y)$ is a function of y and acts as the constant of integration. Furthermore, if we take the partial derivative of $F(x, y)$ with respect to $y$ we obtain $\frac{\partial F}{\partial y} = xe^{xy} + h'(y)$. We also want a function $F(x,y)$ such that $\frac{\partial F}{\partial y} = N(x, y)$. Hence if we set the two together we see that $3 + xe^{xy} = h'(y) + xe^{xy} + h'(y) \implies 3 = h'(y) \implies 3y + c = h(y)$, however we can choose $c = 0$ in this case since we only need the simplest $h(y)$, and hence $h(y) = 3y$. Thus, since $\int dF(t, y) = 0 \implies F(t, y) = C$, we obtain the general implicit solution $e^{xy} + 3y = C$ where $C \in \mathbb{R}$ is a constant.

3. For the ODE $ye^{xy}dx + (3 + xe^{xy})dy = 0$ find the solution (in implicit form) that satisfies the initial condition $y(0) = 0$.

As computed above, the general explicit solution to the above ODE is $e^{xy} + 3y = C$ where $C \in \mathbb{R}$ is a constant. To solve this IVP we must find the constant $C$ that satisfies the initial condition $y(0)=0$. Plugging in the initial condition into the general solution we obtain $e^{0 \cdot y(0)} + 3y(0) = C \implies C = 1$, hence the particular solution to the IVP is $e^{xy} + 3y = 1$.
